# Generated by Django 4.1.7 on 2023-10-07 14:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elfprogramheader',
            name='p_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None, verbose_name='p_type'),
        ),
        migrations.AlterField(
            model_name='elfsectionheader',
            name='sh_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=14), null=True, size=None, verbose_name='sh_type'),
        ),
    ]
