# Generated by Django 4.2.6 on 2023-10-08 16:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_elfprogramheader_p_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elfsectionheader',
            name='sh_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None, verbose_name='sh_type'),
        ),
    ]
