# Generated by Django 4.2.6 on 2023-10-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_elfsectionheader_sh_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmetadata',
            name='enable_internet',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
