# Generated by Django 4.2.6 on 2023-12-02 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        ('analysis', '0005_taskmetadata_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendToEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.TimeField(null=True)),
                ('pid', models.PositiveSmallIntegerField(null=True)),
                ('procname', models.BinaryField(max_length=128, null=True)),
                ('fd', models.BigIntegerField(null=True)),
                ('buffer', models.BinaryField(max_length=128, null=True)),
                ('size', models.PositiveIntegerField(null=True)),
                ('kernel_trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.kerneltrace')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.samplemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='RecvFromEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.TimeField(null=True)),
                ('pid', models.PositiveSmallIntegerField(null=True)),
                ('procname', models.BinaryField(max_length=128, null=True)),
                ('fd', models.BigIntegerField(null=True)),
                ('buffer', models.BinaryField(max_length=128, null=True)),
                ('size', models.PositiveIntegerField(null=True)),
                ('kernel_trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.kerneltrace')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.samplemetadata')),
            ],
        ),
    ]
