# Generated by Django 4.2.6 on 2024-01-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_pcapanalysis_detection_network_analysis_detectors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnspacketanalysis',
            name='response_class',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='dnspacketanalysis',
            name='response_data',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='dnspacketanalysis',
            name='response_ttl',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dnspacketanalysis',
            name='response_type',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
